services:
  - type: web
    name: connect-wallet-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_TO
        sync: false

  - type: static_site
    name: connect-wallet-client
    rootDir: client
    buildCommand: npm install && npm run build
    publishDir: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_REOWN_PROJECT_ID
        sync: false
      - key: REACT_APP_RECIPIENT_ADDRESS
        sync: false
      - key: REACT_APP_ALCHEMY_API_KEY
        sync: false
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: connect-wallet-server
          property: url
      - key: REACT_APP_SOLANA_RECIPIENT_ADDRESS
        sync: false
      - key: REACT_APP_SOLANA_RPC_URL
        sync: false 